hotfix: wrong export paths, hasAll method and tests
jacwright/array-query pull request #17
Opened 2023-03-30 17:34 UTC by mateusmcordeiro

After the awsome update we`ve done, i tried to install the library inside my project and for my surprise, it was not working hahaha, but i saw it was a easy thing to solve locally and this PR is to solve this for the others users.

it was just a configuration missing on package.json and it is going to need to push a new patch version to npm.

i dont know why no one has opened a issue about it, because i saw the last version number of downloads on npm and its like 60+.

------

I`ve pushed some more code fixing about the hasAll method and added some tests.

2023-04-11 21:06 UTC, jacwright requested changes
Apologies for the bad package.json. Thank you!

The `hasAll` was correct. The tests are a great add, though one of them is incorrect.

2023-04-11 21:06 UTC, jacwright commented on src/lib/query.ts
> +        "%not(%term && %value?.every(value => %term.includes?.(...value)))";
This is incorrect. Here is the simplified code that this turns into before this fix:

```js
function hasAll(obj: any, prop: string, value: any[]) {
  return value.every(item => obj[prop].includes(item));
}
```

To make it more readable, you can change `value => %term.includes?.(value)` to `item => %term.includes?.(item)`, but other than that, it should be left as-is.

2023-04-11 21:06 UTC, jacwright commented on __tests__/query.spec.js
>      );
This is incorrect. It is giving back an empty array and should be:
```js
fruit.characteristics.includes("Juicy", "Sweet")
```
Once you fix this and change `hasAll` back to the way it was, the tests will pass.

2023-04-11 22:56 UTC, mateusmcordeiro commented on src/lib/query.ts
> +        "%not(%term && %value?.every(value => %term.includes?.(...value)))";
i made the tests first, as you saw there i wrote some includes in a  wrong way on the test and i didnt saw it. 

About this, im going to remove this spread on the value.

But it was missing a `)` at the end, this change is right and i will not change it.

2023-04-11 23:03 UTC, merged

2023-04-12 21:54 UTC, jacwright commented
Published as 0.2.2